version: '3'
services:
  mongodb-myapp:
    image: mongo:latest
    container_name: mongodb-myapp
    volumes:
      - mongodb-data:/data/db
    restart: always
    networks:
      - nodeapp-network

  express-mongo-boilerplate:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    container_name: express-mongo-boilerplate
    expose:
      - '5000'
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=dev
      - PORT=${PORT}
      - MONGO_URL=mongodb://mongodb-myapp:27017/node_crud
    command: npm run start:dev
    networks:
      - nodeapp-network
    restart: always
    depends_on:
      - mongodb-myapp



networks:
  nodeapp-network:
    driver: bridge

volumes:
  mongodb-data: {}
